// <auto-generated />
using CoreMVC5_UsedBookProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreMVC5_UsedBookProject.Migrations
{
    [DbContext(typeof(AccountContext))]
    [Migration("20230612131447_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreMVC5_UsedBookProject.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "R001",
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = "R002",
                            Name = "Sales"
                        },
                        new
                        {
                            Id = "R003",
                            Name = "RD"
                        },
                        new
                        {
                            Id = "R004",
                            Name = "Operation"
                        });
                });

            modelBuilder.Entity("CoreMVC5_UsedBookProject.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "U001",
                            Email = "kevinxi@gmail.com",
                            Name = "Admin0001",
                            Nickname = "Admin0001",
                            Password = "$2a$11$mqOdtqjWe55qhO6GAIVOI.12UNUaI7u/Hvv8Q6BBsHV7ObA7CW3v.",
                            PhoneNo = "0925-155222"
                        },
                        new
                        {
                            Id = "U002",
                            Email = "marylee@gmail.com",
                            Name = "Admin0002",
                            Nickname = "Admin0002",
                            Password = "$2a$11$n4yAo6X3afNGC23GzUynmukvBV.8UyDitRKwN6Mw7S/Bh155kd1f2",
                            PhoneNo = "0935-123123"
                        },
                        new
                        {
                            Id = "U003",
                            Email = "johnwei@gmail.com",
                            Name = "Admin0003",
                            Nickname = "Admin0003",
                            Password = "$2a$11$Vx0u.FyOFAH2ZKwI1H59I.eJQO47.YjWpfGQ7usz.sdNaIIccaL26",
                            PhoneNo = "0955-456456"
                        });
                });

            modelBuilder.Entity("CoreMVC5_UsedBookProject.Models.UserRoles", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "U001",
                            RoleId = "R001"
                        },
                        new
                        {
                            UserId = "U002",
                            RoleId = "R002"
                        },
                        new
                        {
                            UserId = "U003",
                            RoleId = "R003"
                        },
                        new
                        {
                            UserId = "U003",
                            RoleId = "R004"
                        });
                });

            modelBuilder.Entity("CoreMVC5_UsedBookProject.Models.UserRoles", b =>
                {
                    b.HasOne("CoreMVC5_UsedBookProject.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreMVC5_UsedBookProject.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreMVC5_UsedBookProject.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CoreMVC5_UsedBookProject.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
