// <auto-generated />
using System;
using CoreMVC5_UsedBookProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreMVC5_UsedBookProject.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreMVC5_UsedBookProject.Models.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DenyReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.HasKey("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = "O001",
                            BuyerId = "U002",
                            CreateDate = new DateTime(2023, 6, 28, 9, 1, 2, 610, DateTimeKind.Local).AddTicks(3087),
                            DenyReason = "none",
                            ProductId = "P001",
                            SellerId = "U001",
                            Status = "待確認",
                            Trade = "金錢",
                            UnitPrice = 500m
                        },
                        new
                        {
                            OrderId = "O002",
                            BuyerId = "U002",
                            CreateDate = new DateTime(2023, 6, 28, 9, 1, 2, 610, DateTimeKind.Local).AddTicks(3361),
                            DenyReason = "none",
                            ProductId = "P002",
                            SellerId = "U001",
                            Status = "待確認",
                            Trade = "金錢",
                            UnitPrice = 500m
                        },
                        new
                        {
                            OrderId = "O003",
                            BuyerId = "U002",
                            CreateDate = new DateTime(2023, 6, 28, 9, 1, 2, 610, DateTimeKind.Local).AddTicks(3367),
                            DenyReason = "none",
                            ProductId = "P003",
                            SellerId = "U001",
                            Status = "待確認",
                            Trade = "以物易物",
                            UnitPrice = -1m
                        });
                });

            modelBuilder.Entity("CoreMVC5_UsedBookProject.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicationDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.HasKey("ProductId");

                    b.HasIndex("CreateBy");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = "P001",
                            Author = "作者",
                            ContentText = "Context1",
                            CreateBy = "U001",
                            CreateDate = new DateTime(2023, 6, 28, 9, 1, 2, 607, DateTimeKind.Local).AddTicks(6563),
                            Degree = "二手",
                            EditDate = new DateTime(2023, 6, 28, 9, 1, 2, 609, DateTimeKind.Local).AddTicks(1054),
                            ISBN = "9876543210",
                            Image1 = "example.jpg",
                            Image2 = "無圖片,無圖片,無圖片,無圖片,無圖片,無圖片,無圖片,無圖片",
                            PublicationDate = "2023-01-01",
                            Publisher = "出版社",
                            Status = "未上架",
                            Title = "Book1",
                            Trade = "金錢",
                            UnitPrice = 500m
                        },
                        new
                        {
                            ProductId = "P002",
                            Author = "作者",
                            ContentText = "Context2",
                            CreateBy = "U001",
                            CreateDate = new DateTime(2023, 6, 28, 9, 1, 2, 609, DateTimeKind.Local).AddTicks(1691),
                            Degree = "二手",
                            EditDate = new DateTime(2023, 6, 28, 9, 1, 2, 609, DateTimeKind.Local).AddTicks(1696),
                            ISBN = "9876543211",
                            Image1 = "example.jpg",
                            Image2 = "無圖片,無圖片,無圖片,無圖片,無圖片,無圖片,無圖片,無圖片",
                            PublicationDate = "2023-01-01",
                            Publisher = "出版社",
                            Status = "未上架",
                            Title = "Book2",
                            Trade = "金錢",
                            UnitPrice = 500m
                        },
                        new
                        {
                            ProductId = "P003",
                            Author = "作者",
                            ContentText = "Context3",
                            CreateBy = "U001",
                            CreateDate = new DateTime(2023, 6, 28, 9, 1, 2, 609, DateTimeKind.Local).AddTicks(1701),
                            Degree = "二手",
                            EditDate = new DateTime(2023, 6, 28, 9, 1, 2, 609, DateTimeKind.Local).AddTicks(1702),
                            ISBN = "9876543212",
                            Image1 = "example.jpg",
                            Image2 = "無圖片,無圖片,無圖片,無圖片,無圖片,無圖片,無圖片,無圖片",
                            PublicationDate = "2023-01-01",
                            Publisher = "出版社",
                            Status = "未上架",
                            Title = "Book3",
                            Trade = "以物易物",
                            UnitPrice = -1m
                        });
                });

            modelBuilder.Entity("CoreMVC5_UsedBookProject.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "R001",
                            Name = "Seller"
                        },
                        new
                        {
                            Id = "R002",
                            Name = "Buyer"
                        },
                        new
                        {
                            Id = "R003",
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = "R004",
                            Name = ""
                        });
                });

            modelBuilder.Entity("CoreMVC5_UsedBookProject.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIcon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "U001",
                            Email = "kevinxi@gmail.com",
                            Name = "Admin0001",
                            Nickname = "Admin0001",
                            Password = "$2a$11$YNp1nVpY845sccXlkHq8Juzx/r2DXcNnH/dBOjrYXdTV.E71InqoO",
                            PhoneNo = "0925-155222",
                            UserIcon = "empty.png"
                        },
                        new
                        {
                            Id = "U002",
                            Email = "marylee@gmail.com",
                            Name = "Admin0002",
                            Nickname = "Admin0002",
                            Password = "$2a$11$PBSXe9N4/DA0PeQfouY8muDx8/gWmZJWjg14Y9xkMj4LIVqQNPK26",
                            PhoneNo = "0935-123123",
                            UserIcon = "empty.png"
                        },
                        new
                        {
                            Id = "U003",
                            Email = "johnwei@gmail.com",
                            Name = "Admin0003",
                            Nickname = "Admin0003",
                            Password = "$2a$11$2i7dH/vuRYoE7ua760Bhi.KwnCRE2S6EyJsryq7pWtOWHuZze/uoS",
                            PhoneNo = "0955-456456",
                            UserIcon = "empty.png"
                        });
                });

            modelBuilder.Entity("CoreMVC5_UsedBookProject.Models.UserRoles", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "U001",
                            RoleId = "R001"
                        },
                        new
                        {
                            UserId = "U002",
                            RoleId = "R001"
                        },
                        new
                        {
                            UserId = "U003",
                            RoleId = "R001"
                        },
                        new
                        {
                            UserId = "U001",
                            RoleId = "R002"
                        },
                        new
                        {
                            UserId = "U002",
                            RoleId = "R002"
                        },
                        new
                        {
                            UserId = "U003",
                            RoleId = "R002"
                        },
                        new
                        {
                            UserId = "U001",
                            RoleId = "R003"
                        },
                        new
                        {
                            UserId = "U002",
                            RoleId = "R003"
                        },
                        new
                        {
                            UserId = "U003",
                            RoleId = "R003"
                        });
                });

            modelBuilder.Entity("CoreMVC5_UsedBookProject.Models.Order", b =>
                {
                    b.HasOne("CoreMVC5_UsedBookProject.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CoreMVC5_UsedBookProject.Models.Product", b =>
                {
                    b.HasOne("CoreMVC5_UsedBookProject.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("CreateBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreMVC5_UsedBookProject.Models.UserRoles", b =>
                {
                    b.HasOne("CoreMVC5_UsedBookProject.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreMVC5_UsedBookProject.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreMVC5_UsedBookProject.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CoreMVC5_UsedBookProject.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
